### ISSUE TITLE
[ENHANCEMENT] file cache geocoding api link for each known spawnpoint

### ISSUE THREAD

**Issue by gregbrahe** [PokeAlarm/PokeAlarm#509]
## Description
I was chatting with Legit Dongo on the discord and he suggested that I submit this here. While caching whatever other information is cached using {file} caching, please consider also caching a the link that google geocoding api produces as well as the address for each unique spawnpoint.

## Why is this enhancement necessary or useful?
Google api can be expensive, especially when using loose filters and scanning a large area. While there are workarounds for this, I think that your users as well as google would greatly appreciate if the server load was reduced by simply caching the information they provide rather than requesting it anew every time something spawns at any particular point.

## How can this enhancement be accomplished?
I really don't know enough about programming to offer anything here, but I do know that my database table for spawnpoints across several Midwestern cities is just under 57,000 spawnpoints right now (while extra spawnpoints are active due to gen3 launch). The table is a mere 13 MiB, and that doesn't seem that unreasonable as a cache file, although even that would be larger than any cache file would need to be since I have multiple managers running dividing out the area. Those tables include the latitude and longitude coordinates, but also a few other columns of various information, and it seems like caching only the url of a google maps link and an address would take less space than that. Doing this could save your users untold amounts of money. My google api bill was $121 in October because of the ghost event and scanning for shinies! Please give us the option to bear that load on our own systems rather than constantly sending requests!

**Comment by kvangent** [comment]
Hello! Thanks for taking the time to submit a feature request. 

Static maps are just urls sent to discord/slack - they can't be cached because slack/discord calls them (and they likely do their own caching)

Reverse geocoding can't be cached to a file because it's against the TOS. You could disable reverse geocoding to cut down on your costs.

**Comment by rly** [comment]
The Google Maps API TOS allows for caching their data for up to 30 days: https://developers.google.com/maps/terms#section_10_5

Would it be reasonable to implement a lite database for caching reverse geocoded addresses and have it refresh entries every 30 days (on a rolling basis)? We hit our quota of 2500 calls/day in the middle of the day, and something like this would really help. Thanks.

**Comment by kvangent** [comment]
@rly So specifically, the part that matters here is:

> You will not pre-fetch, cache, index, or store any Content to be used *outside the Service*, except that you may store limited amounts of Content solely for the purpose of improving the performance of your Maps API Implementation due to network latency

When we dump the data to another medium, it's leaving the service. Further more, the TOS continues:

 >* is temporary (and in no event more than 30 calendar days);
>* is secure;

The storage of the data into a database isn't *really* temporary (even if we wipe it every 30 days), and it isn't secure because other users/processes can access it. By keeping the cache in memory is is temporary and it is secure and it is inside the service. 

If the 2500 quota is an issue, you simply need to flip the switch and start paying for this service they so generally provide freely (in small amounts), or you need to start being more choosy about which events you want to use those DTS on.

**Comment by rly** [comment]
@kvangent Ah, I understand. Thank you for the comprehensive reply! We are now trying out showing the google maps static images instead of addresses, which are equally, if not more, informative than addresses, and have the benefit of a higher quota limit (10k loads/day).
