### ISSUE TITLE
[FEATURE ENHANCEMENT] Allow filters to call specific alarms - multiple alarms of same type

### ISSUE THREAD

**Issue by robertrothberg** [PokeAlarm/PokeAlarm#553]
## Description
Currently I cannot find a simple way to have filters of the same type (ie monster_1, monster_2) to call different alarms (ie monsteralarm_1, monsteralarm_2)

## Why is this enhancement necessary or useful?
An example of this is when sending messages to Discord, I would like to send different alarms of the same type to the same webhook. 
ie, filter_1 is for 100IV, calls monsteralarm_1 definition that includes the text "@100iv" in the body
filter_2 is for unown, calls monsteralarm_2 (identical to monsteralarm_1 except) it includes the text @unown in the body

The current implementation for this is way too complicated and involves having to create multiple managers and multiple alarm json files (unless I misunderstand, but this is how it was explained to me in the PA discord channel).  

## How can this enhancement be accomplished?
Within alarm.json, allow creation of multiple alarms of the same type (ie multipe monster, raid, etc) and
allow them to be named.  From the filter.json, provide a parameter for alarm name to be called.

**Comment by robertrothberg** [comment]
Here's an example of what I'm thinking.

![unknown](https://user-images.githubusercontent.com/3464225/34955973-f239a24a-f9f4-11e7-89c2-cbcad40ed35f.png)

**Comment by kvangent** [comment]
As I told you in discord, you can optimize your set up a lot using [custom dts](https://github.com/PokeAlarm/PokeAlarm/wiki/Filters-Overview#custom-dts) feature that was added in 3.5. 

You can use it to choose a different mention for each filter.

You can also use it to change the webhook_url to different channels. See the [Getting Started](https://github.com/PokeAlarm/PokeAlarm/wiki/Getting-Started-Guide#advanced-custom-dts) guide for an example of this. 

This is a new feature planned in 3.6 to give you more control over which filters go where, but I'm going to close this because I think your use cases seem covered. 


You can use it for mentions by setting a
