### ISSUE TITLE
[Bug] Custom Telegram stickers bug

### ISSUE THREAD

**Issue by zenoncrow** [PokeAlarm/PokeAlarm#600]
## Troubleshooting Checklist

- [x] My RocketMap install is at the most recent version.  
- [x] My PokeAlarm install is at the most recent version.  
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description
RM and PA themselves function without a problem. But for the previous versions of PA I used custom stickers for Telegram which I imported by editing the file PokeAlarm/PokeAlarm/Telegram/Stickers.py and pasting the sticker_ids I needed instead of the default ones.

However, it's impossible to do so with the newest version of PA. I was told about the new method on Discord, but found a bug.
That's the code I used in the Alarms.json file:

`
"raids":{
        "message":"*bla-bla-bla*",
        "map":true,
	"sticker_url":"http://mysite.com/pokemon/<mon_id_3>.webp"
    }
`
I connected to the ftp-server of mysite.com and put a pokemon folder in there with all the raid-boss sticker files in webp format like so:
`
002.webp
005.webp
008.webp
etc
`
I have a total of all the currently active raid bosses in there plus Rayquaza (32 stickers)
However some of the stickers don't load upon each time I start PA. For example. I started PA, all of the Kyogres are showing up as stickers correctly, all of the Charmeleon, Mawile are showing up as stickers correctly, but all of the Aggron don't show any stickers at all. Restarting PA doesn't fix the problem.

However, if I go to the mysite ftp server and change the name of the folder to, let's say, "pokes" instead of "pokemon" and change the link in the alarms.json to "sticker_url":"http://mysite.com/pokes/<mon_id_3>.webp" other stickers work correctly (all of the Aggron are shown correctly) and others suddenly disappear (Mawile stickers don't show up anymore). And each time I feed PA a new link with the all the same files being in the folder random stickers just either work or they don't.

## Environment
Operating System: Windows 7 Ultimate
Python Version: `2.7.14`  
PokeAlarm Branch: ` master `  
PokeAlarm Version: ` a75fd6e3d35966a2086e804a85bb16cd4acea616 `  

## PokeAlarm Setup:
Your config file: https://pastebin.com/9qCpNp5i
Your filters file: https://pastebin.com/QfPB1ti2
Your alarms file:  https://pastebin.com/TFq219sf
Your rules file: https://pastebin.com/0zXj3T1x

**Comment by kvangent** [comment]
This is probably an issue between your site and Telegram's CDN. Telegram seems to cache even failed URLs, so if their servers fail to grab the image on the first time, it seems to fail every time. It may also be an issue with the images themselves (Telegram wants them to be 512x512 and in the webp format (not just as the extension)).

There are a few things you can try. First of all, make sure your server is responsive and quick and servers the proper image. If you are using cloudflare caching, make sure you clear it every time you update your url. Second, try adding in some parameter to bust Telegram's cache (ie, "089.png?cachebust=0001"). Finally, you may want to use https on your server (some sites reject http since it is not secure).

I don't think this is an issue on PA's side, since PA just sends a post request with the URL. You can mock up a similar request to `https://api.telegram.org/bot1111111111/sendSticker` (replace the ones with your bot token) with the following payload:
```json
{
    "chat_id": "your-chat-id",
    "sticker": "your-sticker-url",
    "disable_notification": true
}
```

If you determine this is in fact an issue with PA, please feel free to reopen with an explanation of why.
