### ISSUE TITLE
[Discord] Error during gym webhook: UnicodeDecodeError: 'utf8' cannot decode bytes

### ISSUE THREAD

**Issue by Su9m7** [PokeAlarm/PokeAlarm#651]
## Troubleshooting Checklist

- [x] My RocketMap install is at the most recent version.  
- [x] My PokeAlarm install is at the most recent version.  
- [x] I've already checked the
 [FAQ](https://github.com/RocketMap/PokeAlarm/wiki/faq) and the
 [Wiki](https://github.com/RocketMap/PokeAlarm/wiki) already.  

## Problem Description
Sometimes, I do not receive notifications for some Raids. You can see the error code in the pastebin below.
https://pastebin.com/aAi8YsZ3
It often happens at a gym, that is not scanned permanently, because there are only a few spawnpoints in that area. (Most of the time my workers see the spawned Raid ~5min after appearing)

## Environment
Operating System: Windows Server 2016 Standard
Python Version: 2.7.12 
PokeAlarm Branch: master
PokeAlarm Version: 3f6b7c330bc9cff96ff3a65dc2252c374141209a  

## PokeAlarm Setup:

Your config file: https://pastebin.com/8YBwiN5E  
Your filters file: https://pastebin.com/rijF03yT 
Your alarms file:  https://pastebin.com/h3xxBeXQ  

## Log Output

I hat to delete many lines, because it would be too long.
Here is the log with the important parts(boot up and error):
https://hastebin.com/adivezakol.md

**Comment by kvangent** [comment]
I tried to test your filters out, and I can't even load the file because of the emojis. My guess is that is your issue. You really should be using the unicode id for non-ascii characters. 

See if you can replicate the issue with the webhook tester. Use one gym and rotate between teams and see if they all work correctly. If you can replicate reliably, try replacing the emojis with other characters and see if it starts working.

**Comment by Su9m7** [comment]
I tested it with the gym(it has a "ä" in its gym name), where the issue occurs most of the time. With the test tool, it's all working fine, not a single error.
But I have noticed that the test tool does not send the gym name to the webhook. Could it be possible, that the letter "ä" is the problem?

**Comment by kvangent** [comment]
It's not for my setup, but it could be on Windows. Did you try with all of the teams to tests all of your custom_dts?

**Comment by Su9m7** [comment]
Yes, I tested it with all teams.

**Comment by kvangent** [comment]
Please PM me your filters, alarms, and the name of the gym  on Discord.

**Comment by kvangent** [comment]
Ok, this is definitely user-specific and is definitely because of the emojis used in your egg alarms. Specifically, it happens when sending L2 Mystic Eggs. Removing `<teamname1>` solved the problem for me.

(I had originally marked this up to `bug` because I thought I had confirmed the team name, but I was wrong)

**Comment by Su9m7** [comment]
I changed the emojis to discord emojis. Tested it with the test tool. Can tell if its working 100% of the time, when hashing is back up(If ever).
