### ISSUE TITLE
Adjusting DTS <form_or_empty> to omit normalform

### ISSUE THREAD

**Issue by Audidriver13** [pokealarm/pokealarm#816]
## Description

Since PR #802 the DTS <form_or_empty> always return "Normal Form" instead of leaving it blank as before when no specific form was recognized. Since 95% of the reported pokémon are normal form and the text takes up a lot of space in all languages, it would be beneficial to omit the form DTS when normal form is detected.

**Comment by Pontiky** [comment]
The old behaviour returned a blank text because the forms were not recognized. With #802, all the forms are now correctly recognized et no more `unknown`. According to the doc, `form_or_empty: Form name of the monster, or empty string if unknown.` DTS now works as expected.

> it would be beneficial to omit the form DTS when normal form is detected

In the end, this behaviour needs its proper new DTS.
